import { chromium } from 'playwright-core';
const EXE='/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const browser=await chromium.launch({executablePath:EXE, headless:true, args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1560,height:1150},deviceScaleFactor:2});
await page.goto('file:///home/user/polarization-prototype/figures/fig1-compose.html',{waitUntil:'networkidle'});
await page.waitForTimeout(400);
const fig=await page.$('#fig');
await fig.screenshot({path:'/home/user/polarization-prototype/figures/fig1-interaction.png'});
await page.pdf({path:'/home/user/polarization-prototype/figures/fig1-interaction.pdf', width:(1560/96)+'in', height:(1150/96)+'in', printBackground:true, pageRanges:'1'});
await browser.close(); console.log('composed');
